### ISSUE TITLE
NavicatPremium@8: decompress error

### ISSUE THREAD

**Issue by danniserena** [akirco/aki-apps#1]
I am using scoop to automatically install NavicatePremiun and found this issue:
----
Failed to extract files from D:\scoop\apps\NavicatPremium\8\NavicatPremium-8.7z.
Log file:
  D:\scoop\apps\NavicatPremium\8\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/akirco/aki-apps/issues/new?title=NavicatPremium%408%3a+decompress+error

-------
I went to the dir where I installed the app and tried to unzip it with 7-Zip. An error showed: cannot open as a compressed file.

**Comment by akirco** [comment]
I recommend you to use the database management software that comes with `IDEA`or the `data grip` of the `jetbrains` family, it is very easy to use, this will be deleted by me

**Comment by akirco** [comment]
> ## I am using scoop to automatically install NavicatePremiun and found this issue:
> Failed to extract files from D:\scoop\apps\NavicatPremium\8\NavicatPremium-8.7z. Log file: D:\scoop\apps\NavicatPremium\8\7zip.log
> 
> Please try again or create a new issue by using the following link and paste your console output: https://github.com/akirco/aki-apps/issues/new?title=NavicatPremium%408%3a+decompress+error
> 
> I went to the dir where I installed the app and tried to unzip it with 7-Zip. An error showed: cannot open as a compressed file.

**Comment by akirco** [comment]
> ## I am using scoop to automatically install NavicatePremiun and found this issue:
> Failed to extract files from D:\scoop\apps\NavicatPremium\8\NavicatPremium-8.7z. Log file: D:\scoop\apps\NavicatPremium\8\7zip.log
> 
> Please try again or create a new issue by using the following link and paste your console output: https://github.com/akirco/aki-apps/issues/new?title=NavicatPremium%408%3a+decompress+error
> 
> I went to the dir where I installed the app and tried to unzip it with 7-Zip. An error showed: cannot open as a compressed file.

I recommend you to use the database management software that comes with `idea` or the `data grip` of the `jetbrains` family, it is very easy to use, this will be deleted by me
