### ISSUE TITLE
pikpak@1.1.1: hash check failed

### ISSUE THREAD

**Issue by ALLENYGY** [akirco/aki-apps#10]
Checking hash of official_PikPak.exe ... ERROR Hash check failed!
App:         akirco_aki-apps/pikpak
URL:         https://static.mypikpak.com/desktop/official_PikPak.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    62a77779066dd851162a9e417afa86927a7332d30c6ad3b4ba5e4a6b1cef2e38
Actual:      5031b388f6ab0b19773d57feeb596a2f844411e6d2f1ca55950fd6bdd864eed0

**Comment by akirco** [comment]
@ALLENYGY thx,fix completed.
