### ISSUE TITLE
innounpacker@1.9.2: hash check failed

### ISSUE THREAD

**Issue by zhangyvzhen** [akirco/aki-apps#17]
PS C:\Users\zyz> scoop download innounpacker
INFO  Downloading 'innounpacker' [64bit] from aki bucket
innounpacker.zip (1.9 MB) [===================================================================================] 100%
Checking hash of innounpacker.zip ... ERROR Hash check failed!
App:         aki/innounpacker
URL:         https://www.rathlev-home.de/tools/download/innounpacker.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    9c38b4906fb071e989180a698719b6a364ad2d659d714b0155bada91b64afb9c
Actual:      a76ab5fb40b6eb8a1886a60ac453a937ed2dd71dad7f9c51578cde9b558f88b0
ERROR
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/akirco/aki-apps/issues/new?title=innounpacker%401.9.2%3a+hash+check+failed
'innounpacker' (1.9.2) was downloaded successfully!

**Comment by akirco** [comment]
@zhangyvzhen ok了
