### ISSUE TITLE
安装失败：服务器源下载失败，下载软件为quarkpan

### ISSUE THREAD

**Issue by dgqyushen** [akirco/aki-apps#6]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://pdds-c1-cdn.uc.cn/82-4/stfile/2302/d15d6235efd778c30d21b247e964938e/QuarkCloudDrive-2.5.10-win-release1.exe?auth_key=1676601112-0-0-1ad7806b63ddc87412ce8ffc8fd3cebe&SESSID=639f383461935cccc8086be7574b3a08&ext=uc.exe#/dl.7z
    referer=https://pdds-c1-cdn.uc.cn/82-4/stfile/2302/d15d6235efd778c30d21b247e964938e/QuarkCloudDrive-2.5.10-win-release1.exe?auth_key=1676601112-0-0-1ad7806b63ddc87412ce8ffc8fd3cebe&SESSID=639f383461935cccc8086be7574b3a08&ext=uc.exe#/
    dir=D:\Scoop\cache
    out=quarkpan#2.5.10#https_pdds-c1-cdn.uc.cn_82-4_stfile_2302_d15d6235efd778c30d21b247e964938e_QuarkCloudDrive-2.5.10-win-release1.exe_auth_key_1676601112-0-0-1ad7806b63ddc87412ce8ffc8fd3cebe_SESSID_639f383461935cccc8086be7574b3a08_ext_uc.exe_dl.7z

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\quarkpan.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=32 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8668 --continue --summary-interval=0 --auto-save-interval=1

**Comment by akirco** [comment]
it's ok.

**Comment by akirco** [comment]
> ERROR Download failed! (Error 22) HTTP response header was bad or unexpected ERROR https://pdds-c1-cdn.uc.cn/82-4/stfile/2302/d15d6235efd778c30d21b247e964938e/QuarkCloudDrive-2.5.10-win-release1.exe?auth_key=1676601112-0-0-1ad7806b63ddc87412ce8ffc8fd3cebe&SESSID=639f383461935cccc8086be7574b3a08&ext=uc.exe#/dl.7z referer=https://pdds-c1-cdn.uc.cn/82-4/stfile/2302/d15d6235efd778c30d21b247e964938e/QuarkCloudDrive-2.5.10-win-release1.exe?auth_key=1676601112-0-0-1ad7806b63ddc87412ce8ffc8fd3cebe&SESSID=639f383461935cccc8086be7574b3a08&ext=uc.exe#/ dir=D:\Scoop\cache out=quarkpan#2.5.10#https_pdds-c1-cdn.uc.cn_82-4_stfile_2302_d15d6235efd778c30d21b247e964938e_QuarkCloudDrive-2.5.10-win-release1.exe_auth_key_1676601112-0-0-1ad7806b63ddc87412ce8ffc8fd3cebe_SESSID_639f383461935cccc8086be7574b3a08_ext_uc.exe_dl.7z
> 
> ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\quarkpan.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=32 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8668 --continue --summary-interval=0 --auto-save-interval=1

it's ok
