### ISSUE TITLE
ffmpeg@6.0: hash check failed

### ISSUE THREAD

**Issue by zero617** [akirco/aki-apps#8]
App:         akirco_aki-apps/ffmpeg
URL:         https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.0-full_build.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    75acdf3afe0409b294cb2b76216ecbe5299782970688617259ffbc22679872e8
Actual:      eb65985adbb6ab1c93dec2b22a3628f6d6a309d0bc5bbdd1e3696f0980905cad

**Comment by akirco** [comment]
> App: akirco_aki-apps/ffmpeg URL: https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.0-full_build.7z First bytes: 37 7A BC AF 27 1C 00 04 Expected: 75acdf3afe0409b294cb2b76216ecbe5299782970688617259ffbc22679872e8 Actual: eb65985adbb6ab1c93dec2b22a3628f6d6a309d0bc5bbdd1e3696f0980905cad

i fix it,thx
