### ISSUE TITLE
mysql@8.1.0: hash check failed

### ISSUE THREAD

**Issue by zero617** [akirco/aki-apps#9]
Downloading https://dev.mysql.com/get/Downloads/MySQL-8.1/mysql-8.1.0-winx64.zip (236.9 MB)...
Checking hash of mysql-8.1.0-winx64.zip ... ERROR Hash check failed!
App:         akirco_aki-apps/mysql
URL:         https://dev.mysql.com/get/Downloads/MySQL-8.1/mysql-8.1.0-winx64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    453d729afa2697a7a79d067830e071a6
Actual:      40a977d01e565b1d751ca068c823ba16

**Comment by akirco** [comment]
thx,fix completed.
